### ISSUE TITLE
Build instructions for v1.0.8-win-cross

### ISSUE THREAD

**Issue by Candunc** [radix42/zcash#9]
Hello,

I tried to build the v1.0.8-win-cross branch however the only installation instructions I could find was from [v1.0.4-win-native](https://github.com/radix42/zcash/blob/v1.0.4-win-native/README-win.md) however I have a large error involving "syntax error near unexpected token `|'" with both the v1.0.8-win-native branch as well as v1.0.8-win-cross. Is there build instructions for the latest build?

**Comment by Candunc** [comment]
I figured out the build instructions and wrote them down on my own fork [here](https://github.com/Candunc/zcash/tree/v1.0.10-1-win-cross)

**Comment by radix42** [comment]
sorry for the sparse docs right now! very few people have contacted me
about building for windows from source, so I have let that slip down the
priority list
